name: Build Typst document
on: push

permissions:
  contents: write
  
jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: Master.typ
      - name: Publish latest PDF
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: Latest
          allowUpdates: true
          replacesArtifacts: true
          artifacts: Master.pdf
